apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-load
spec:
  template:
    spec:
      volumes:
        - name: parameters
          emptyDir: { }
      initContainers:
        - name: parameters-pull
          image: docker.io/madhanmohanreddyeeda/github-repo-parameter-store-init-container-image
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: "dev.roboshop.rds.endpoint,DB_HOST dev.roboshop.rds.username,DB_USER dev.roboshop.rds.password,DB_PASS"
      containers:
        - name: schema-load
          image: docker.io/madhanmohanreddyeeda/github-repo-schema-loader
          imagePullPolicy: Always
          env:
            - name: COMPONENT
              value: { { .Values.component } }
            - name: SCHEMA_TYPE
              value: { { .Values.schema_type } }
          volumeMounts:
            - mountPath: /parameters
              name: parameters
      restartPolicy: Never
  backoffLimit: 4