apiVersion: batch/v1
kind: Job
metadata:
  name: { { .Values.component } }-schema-load
spec:
  backoffLimit: 4
  template:
    spec:
      volumes:
        - name: parameters
          emptyDir: {}
      initContainers:
        - name: parameters-pull
          image: docker.io/madhanmohanreddyeeda/github-repo-parameter-store-init-container-image
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /parameters
              name: parameters
          env:
            - name: PARAMS
              value: {{ .Values.job.PARAMS }}
      containers:
        - name: schema-load
          image: docker.io/madhanmohanreddyeeda/github-repo-schema-loader
          imagePullPolicy: Always
          env:
            - name: COMPONENT
              value: { { .Values.component } }
            - name: SCHEMA_TYPE
              value: { { .Values.schema_type } }
          volumeMounts:
            - mountPath: /parameters
              name: parameters
      restartPolicy: Never